import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  contentWrapper: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  title: {
    fontSize: 15,
    color: '#888',
    marginBottom: 16,
  },
  addButton: {
    backgroundColor: '#3B5BDB',
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginBottom: 5,
    paddingHorizontal: 18,
    height: 44,
    justifyContent: 'center',
  }, memberButton: {
    backgroundColor: '#008001',
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginBottom: 5,
    paddingHorizontal: 18,
    height: 44,
    justifyContent: 'center',
  }, 
  addButtonLabel: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'none',
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 24,
  },
  vehicleCard: {
    borderRadius: 16,
    backgroundColor: '#fff',
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    padding: 0,
  },
  vehicleCardContent: {
    padding: 16,
    paddingBottom: 12,
  },
  vehicleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  license: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginRight: 10,
    flex: 1,
  },
  statusBadge: {
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 'bold',
    paddingHorizontal: 12,
    paddingVertical: 2,
    marginRight: 8,
    alignSelf: 'center',
    overflow: 'hidden',
    height: 24,
  },
  typeBadge: {
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 2,
    alignSelf: 'center',
    overflow: 'hidden',
    height: 24,
  },
  vehicleInfo: {
    marginBottom: 8,
  },
  infoText: {
    fontSize: 15,
    color: '#222',
    marginBottom: 2,
  },
  infoLabel: {
    fontWeight: 'bold',
    color: '#222',
  },
  removeButton: {
    borderColor: '#F04438',
    borderWidth: 1.5,
    borderRadius: 8,
    // marginTop: 8,
    alignSelf: 'flex-end',
    backgroundColor: '#fff',
    height: 40,
    paddingHorizontal: 18,
  },
  removeButtonLabel: {
    color: '#F04438',
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'none',
  }, ownerBox: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  ownerLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 2,
  },
  ownerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
  },
  vehicleInfo: {
    flex: 2, // Thêm dòng này để chia tỷ lệ với ownerBox
    marginBottom: 8,
    justifyContent: 'center',
  },
  infoText: {
    fontSize: 15,
    color: '#222',
    marginBottom: 2,
  },
});